name: Notify Docs Update

on:
  push:
    branches: [main, master]
    paths:
      - README.md
      - MANUAL.md
  workflow_dispatch:

jobs:
  notify-docs:
    uses: mri-Qbox-Brasil/workflows/.github/workflows/callable-repo-dispatch.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      friendly-name: "Nome do Seu Script" # ⚠️ Altere para o nome do script
      doc-file: "MANUAL.md"
